Mark refreshToken with `@Nullable` in AuthCallback
When passing in null as refreshToken in TokenPair (which is marked as
`@Nullable`) from AuthCallback, then Kotlin will complain about the
`@NonNull` refreshToken being passed into the authenticate() method.

```
    java.io.IOException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter refreshToken
        at android.accounts.AccountManager.convertErrorToException(AccountManager.java:2537)
        at android.accounts.AccountManager.access$700(AccountManager.java:162)
        at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:2388)
        at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:107)
        at android.os.Binder.execTransactInternal(Binder.java:1032)
        at android.os.Binder.execTransact(Binder.java:1005)
```

Fix this by marking the refreshToken parameter as `@Nullable`.